# permissions for end users to view carriers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: carrier-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kb
    app.kubernetes.io/part-of: kb
    app.kubernetes.io/managed-by: kustomize
  name: carrier-viewer-role
rules:
- apiGroups:
  - controller.xiaofeng.cloud
  resources:
  - carriers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - controller.xiaofeng.cloud
  resources:
  - carriers/status
  verbs:
  - get
