---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps/v1
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controller.xiaofeng.cloud
  resources:
  - carriers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controller.xiaofeng.cloud
  resources:
  - carriers/finalizers
  verbs:
  - update
- apiGroups:
  - controller.xiaofeng.cloud
  resources:
  - carriers/status
  verbs:
  - get
  - patch
  - update
