apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrier-controller
spec:
  selector:
    matchLabels:
      controller: carrier-controller
  template:
    metadata:
      labels:
        controller: carrier-controller
    spec:
      containers:
      - name: carrier-controller
        image: tr1stanzhi/carrier:latest
        imagePullPolicy: Always

